jobs:
  include:
  - stage: unit tests
    script: echo 'unit test'
  - stage: deploy to alpha
    language: android
    sudo: required
    jdk: oraclejdk8
    components:
    - build-tools-27.0.3
    - android-28
    - extra
    licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+
    - platforms;android-.+
    install:
    - bundle install
    script:
    - "./gradlew assembleRelease"
before_install:
- mkdir keystore
- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv -in fastlane.json.enc -out fastlane.json -d
- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv -in android.jks.enc -out keystore/android.jks -d
