jobs:
  include:
    - stage: unit tests
      script: "echo 'unit test'"
    - stage: deploy to alpha
      language: android
      sudo: required
      jdk: oraclejdk8
      components:
        - build-tools-28.0.0
        - android-28
        - extra
      licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      install:
        - bundle install
      script:
#        - bundle ex ec fastlane beta
        - ./gradlew assembleRelease
