env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3

jobs:
  include:
  - stage: unit tests
    script: echo 'unit test'
  - stage: deploy to alpha
    language: android
    sudo: required
    jdk: oraclejdk8
    licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
    install:
    - bundle install
#    d56f5187479451eabf01fb78af6dfcb131a6481e
    script:
    - cat local.properties
    - "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
#- mkdir keystore
#- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
#  -in fastlane.json.enc -out fastlane.json -d
#- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
#  -in android.jks.enc -out keystore/android.jks -d
