jobs:
  include:
    - stage: unit tests
      script: "echo 'unit test'"
    - stage: deploy to alpha
      language: android
      sudo: required
      jdk: oraclejdk8
      components:
        - build-tools-28.0.0
        - android-28
        - extra
      install:
        - bundle install
      script:
        - fastlane beta
