jobs:
  include:
    - stage: unit tests
      script: "echo 'unit test'"
    - stage: deploy to alpha
      language: objective-c
      osx_image: xcode8.3
      install:
        - bundle install
      script:
      - export LC_ALL=en_US.UTF-8
      - export LANG=en_US.UTF-8
      - ls
      - gem install fastlane
      - rvm use system
      - gem install CFPropertyList
      - gem install sqlite3
      - rvm use 2.0.0
      - fastlane beta
