env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.0

jobs:
  include:
  - stage: unit tests
    script: echo 'unit test'
  - stage: deploy to alpha
    language: android
    sudo: required
    jdk: oraclejdk8
    android:
      components:
      - tools
      - platform-tools
      - tools
      # The BuildTools version used by your project
      - build-tools-28.0.0
      - android-28
    install:
    - bundle install
    script:
    - "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
