jobs:
  include:
  - stage: unit tests
    script: echo 'unit test'
  - stage: deploy to alpha
    language: android
    sudo: required
    jdk: oraclejdk8
    components:
    - tools
    - build-tools-27.0.3
    - android-28
    - platform-tools
    - extra
    install:
    - bundle install
    script:
    - "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
#- mkdir keystore
#- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
#  -in fastlane.json.enc -out fastlane.json -d
#- openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
#  -in android.jks.enc -out keystore/android.jks -d
