env:
 global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.0

jobs:
  include:
  - stage: unit tests
    script: echo 'unit test'
  - stage: deploy to alpha
    language: android
    sudo: required
    jdk: oraclejdk8
    android:
      components:
        - tools
        - platform-tools
        - tools
        # The BuildTools version used by your project
        - build-tools-28.0.0
        - build-tools-27.0.3
        - android-28
        - extra-google-m2repository
        - extra-android-m2repository
    before_install:
      - sudo apt-get install ant
      - openssl aes-256-cbc -K $encrypted_d7cb9d5df8de_key -iv $encrypted_d7cb9d5df8de_iv
        -in secrets.tar.enc -out secrets.tar -d
      - tar xvf secrets.tar
      - gem update --system
      - gem install fastlane --no-rdoc --no-ri --no-document --quiet
      - pip install --user awscli
      - export LC_ALL=en_US.UTF-8
      - export LANG=en_US.UTF-8
    install:
      - bundle install
      - bundle update fastlane
      - echo y | sdkmanager "ndk-bundle"
      - echo y | sdkmanager "cmake;3.6.4111459"
      - echo y | sdkmanager "lldb;3.1"
    script:
#      - "./gradlew assembleRelease"
      - bundle exec fastlane init
      - bundle exec fastlane supply init
      - bundle exec fastlane alpha

